### ISSUE TITLE
how to install this plugin

### ISSUE THREAD

**Issue by davidcaceres1512** [TheKodeToad/BetterThemes#1]

**Comment by TheKodeToad** [comment]
https://github.com/TheKodeToad/BetterThemes/releases/download/dev-1/io.toadlabs.betterthemes-1.0.0-SNAPSHOT.jar

It kind of works :P. You put it in the dropins folder.
*Really really* not finished though.

**Comment by TheKodeToad** [comment]
I won't lock but this isn't an issue (i realise unless i enable discussions it's hard to ask questions)
